# This pod mounts the nfs volume claim into /usr/share/nginx/html and
# serves a simple web page.

apiVersion: v1
kind: ReplicationController
metadata:
  name: TTT
spec:
  replicas: 2
  selector:
    role: TTT
  template:
    metadata:
      labels:
        role: TTT
    spec:
      containers:
      - name: web
        image: nginx
        ports:
          - name: web
            containerPort: 80
